apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "docling-serve.fullname" . }}
  labels:
    {{- include "docling-serve.labels" . | nindent 4 }}
data:
  DOCLING_SERVE_ENABLE_UI: {{ .Values.config.enableUi | quote }}
  {{- if .Values.config.artifactsPath }}
  DOCLING_SERVE_ARTIFACTS_PATH: {{ .Values.config.artifactsPath | quote }}
  {{- end }}
